"""Test cases for problem 0002 — Conditional Routing (FizzBuzz Graph).

Do not edit this file. Run it (or the whole folder) with pytest:

    pytest problems/0002_conditional_routing -v

In PyCharm: open this file and click the green ▶ next to a test.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

import pytest

from solution import build_graph


@pytest.fixture(scope="module")
def graph():
    return build_graph()


def run(graph, n: int) -> str:
    return graph.invoke({"n": n})["output"]


def test_returns_compiled_graph(graph):
    assert hasattr(graph, "invoke"), "build_graph() must return a COMPILED graph (call .compile())."


def test_fizz(graph):
    for n in (3, 6, 9, 18, 21):
        assert run(graph, n) == "Fizz", f"n={n} should be Fizz"


def test_buzz(graph):
    for n in (5, 10, 20, 25, 50):
        assert run(graph, n) == "Buzz", f"n={n} should be Buzz"


def test_fizzbuzz(graph):
    for n in (15, 30, 45, 60, 90):
        assert run(graph, n) == "FizzBuzz", f"n={n} should be FizzBuzz"


def test_plain_number(graph):
    for n in (1, 2, 7, 11, 13, 17):
        assert run(graph, n) == str(n), f"n={n} should be the number as text"


def test_fifteen_checked_before_three_and_five(graph):
    # The classic trap: 15 must not be caught by the "3" or "5" rule.
    assert run(graph, 15) == "FizzBuzz"
    assert run(graph, 30) == "FizzBuzz"


def test_has_all_branch_nodes(graph):
    nodes = set(graph.get_graph().nodes)
    for name in ("fizzbuzz", "fizz", "buzz", "number"):
        assert name in nodes, f'Expected a node named "{name}", found: {sorted(nodes)}'
