"""Test cases for problem 0005 — Accumulating State with a Reducer.

Do not edit this file. Run it (or the whole folder) with pytest:

    pytest problems/0005_reducer_accumulate -v

In PyCharm: open this file and click the green ▶ next to a test.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

import pytest

from solution import build_graph


@pytest.fixture(scope="module")
def graph():
    return build_graph()


def test_returns_compiled_graph(graph):
    assert hasattr(graph, "invoke"), "build_graph() must return a COMPILED graph (call .compile())."


def test_final_n(graph):
    # 3 -> 6 -> 7 -> 49
    assert graph.invoke({"n": 3, "log": []})["n"] == 49
    # 5 -> 10 -> 11 -> 121
    assert graph.invoke({"n": 5, "log": []})["n"] == 121


def test_log_accumulates_all_three_steps(graph):
    log = graph.invoke({"n": 3, "log": []})["log"]
    assert log == [
        "doubled to 6",
        "incremented to 7",
        "squared to 49",
    ], f"log did not accumulate correctly: {log}"


def test_reducer_is_present(graph):
    # Without a reducer, `log` would be overwritten and keep only the LAST entry.
    log = graph.invoke({"n": 5, "log": []})["log"]
    assert len(log) == 3, (
        "Expected 3 accumulated log entries. If you got 1, `log` is overwriting instead of "
        "accumulating — add a reducer with Annotated[list[str], add]."
    )
    assert log[0] == "doubled to 10"
    assert log[-1] == "squared to 121"


def test_reducer_merges_with_initial_log(graph):
    # The reducer also combines with whatever log we pass in initially.
    log = graph.invoke({"n": 3, "log": ["start"]})["log"]
    assert log == [
        "start",
        "doubled to 6",
        "incremented to 7",
        "squared to 49",
    ], f"reducer should append onto the initial log, got: {log}"


def test_has_all_nodes(graph):
    nodes = set(graph.get_graph().nodes)
    for name in ("double", "increment", "square"):
        assert name in nodes, f'Expected a node named "{name}", found: {sorted(nodes)}'
