"""Test cases for problem 0004 — Calculator (Nested Routing).

Do not edit this file. Run it (or the whole folder) with pytest:

    pytest problems/0004_calculator_nested_routing -v

In PyCharm: open this file and click the green ▶ next to a test.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

import pytest

from solution import build_graph


@pytest.fixture(scope="module")
def graph():
    return build_graph()


def run(graph, a: int, b: int, op: str) -> dict:
    return graph.invoke({"a": a, "b": b, "op": op})


def test_returns_compiled_graph(graph):
    assert hasattr(graph, "invoke"), "build_graph() must return a COMPILED graph (call .compile())."


def test_add(graph):
    r = run(graph, 4, 5, "+")
    assert r["result"] == 9
    assert r["message"] == "4 + 5 = 9"


def test_sub(graph):
    r = run(graph, 9, 4, "-")
    assert r["result"] == 5
    assert r["message"] == "9 - 4 = 5"


def test_mul(graph):
    r = run(graph, 6, 7, "*")
    assert r["result"] == 42
    assert r["message"] == "6 * 7 = 42"


def test_div_integer(graph):
    r = run(graph, 10, 3, "/")
    assert r["result"] == 3           # integer division
    assert r["message"] == "10 / 3 = 3"


def test_div_exact(graph):
    r = run(graph, 20, 5, "/")
    assert r["result"] == 4
    assert r["message"] == "20 / 5 = 4"


def test_div_by_zero(graph):
    r = run(graph, 10, 0, "/")
    assert r["result"] == 0
    assert r["message"] == "division by zero"


def test_div_by_zero_does_not_crash_for_other_ops(graph):
    # b == 0 is only special for division; multiplication by zero is fine.
    r = run(graph, 7, 0, "*")
    assert r["result"] == 0
    assert r["message"] == "7 * 0 = 0"


def test_has_all_nodes(graph):
    nodes = set(graph.get_graph().nodes)
    for name in ("add", "sub", "mul", "check_div", "div_ok", "div_error"):
        assert name in nodes, f'Expected a node named "{name}", found: {sorted(nodes)}'
