"""Test cases for problem 0003 — Grade Pipeline (Consolidation).

Do not edit this file. Run it (or the whole folder) with pytest:

    pytest problems/0003_grade_pipeline -v

In PyCharm: open this file and click the green ▶ next to a test.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

import pytest

from solution import build_graph


@pytest.fixture(scope="module")
def graph():
    return build_graph()


def msg(graph, score: int) -> str:
    return graph.invoke({"score": score})["message"]


def test_returns_compiled_graph(graph):
    assert hasattr(graph, "invoke"), "build_graph() must return a COMPILED graph (call .compile())."


def test_grade_a(graph):
    for score in (90, 95, 100):
        assert msg(graph, score) == f"{score}: A"


def test_grade_pass(graph):
    for score in (60, 75, 89):
        assert msg(graph, score) == f"{score}: Pass"


def test_grade_fail(graph):
    for score in (0, 30, 59):
        assert msg(graph, score) == f"{score}: Fail"


def test_boundaries(graph):
    assert msg(graph, 90) == "90: A"
    assert msg(graph, 89) == "89: Pass"
    assert msg(graph, 60) == "60: Pass"
    assert msg(graph, 59) == "59: Fail"


def test_clamping(graph):
    assert msg(graph, 150) == "100: A"   # clamped down to 100
    assert msg(graph, 1000) == "100: A"
    assert msg(graph, -5) == "0: Fail"   # clamped up to 0
    assert msg(graph, -999) == "0: Fail"


def test_normalized_field_is_set(graph):
    result = graph.invoke({"score": 150})
    assert result["normalized"] == 100
    assert result["grade"] == "A"


def test_has_all_nodes(graph):
    nodes = set(graph.get_graph().nodes)
    for name in ("clamp", "grade_a", "grade_pass", "grade_fail", "finalize"):
        assert name in nodes, f'Expected a node named "{name}", found: {sorted(nodes)}'
