"""Test cases for problem 0001 — Your First StateGraph.

Do not edit this file. Run it (or the whole folder) with pytest:

    pytest problems/0001_first_stategraph -v

In PyCharm: open this file and click the green ▶ next to a test.
"""

import sys
from pathlib import Path

# Make `solution.py` importable no matter where pytest is launched from.
sys.path.insert(0, str(Path(__file__).parent))

import pytest

from solution import build_graph


@pytest.fixture(scope="module")
def graph():
    return build_graph()


def test_returns_compiled_graph(graph):
    # A compiled graph is runnable: it must expose .invoke().
    assert hasattr(graph, "invoke"), "build_graph() must return a COMPILED graph (call .compile())."


def test_greets_ada(graph):
    result = graph.invoke({"name": "Ada"})
    assert result["greeting"] == "Hello, Ada!"


def test_greets_other_names(graph):
    assert graph.invoke({"name": "Linus"})["greeting"] == "Hello, Linus!"
    assert graph.invoke({"name": "Grace"})["greeting"] == "Hello, Grace!"


def test_keeps_name_in_state(graph):
    # The original input key should still be present in the final state.
    result = graph.invoke({"name": "Ada"})
    assert result["name"] == "Ada"


def test_has_node_named_greet(graph):
    nodes = set(graph.get_graph().nodes)
    assert "greet" in nodes, f'Expected a node named "greet", found nodes: {sorted(nodes)}'
